name: alloy
channels:
  - defaults
dependencies:
  - python=3.11
  - pip=23.0.1
  - pip:
    - django==4.2
    - django-environ==0.10.0
    - django-bootstrap-v5==1.0.11
    - django-htmx==1.16.0
    - pandas>=1.1.5
